---
title: "Mod 15 (Wk 9)"
author: "Julianna D."
date: "2023-11-02"
output: html_document
---

# Module 15 Multiple Regression and ANCOVA

```{r}
R = matrix(cbind(1, 0.8, -0.5, 0, 0.8, 1, -0.3, 0.3, -0.5, -0.3, 1, 0.6, 0,
    0.3, 0.6, 1), nrow = 4)
```

```{r}
n <- 1000
k <- 4
M <- NULL
V <- NULL
mu <- c(15, 40, 5, 23)  # vector of variable means
s <- c(5, 20, 4, 15)  # vector of variable SDs
for (i in 1:k) {
    V <- rnorm(n, mu[i], s[i])
    M <- cbind(M, V)
}
M <- matrix(M, nrow = n, ncol = k)
orig <- as.data.frame(M)
names(orig) = c("Y", "X1", "X2", "X3")
head(orig)
```

```{r}
cor(orig)
plot(orig)
```

```{r}
ms <- apply(orig, 2, FUN = "mean") 
ms
```

```{r}
sds <- apply(orig, 2, FUN = "sd")
sds
```

```{r}
normalized <- sweep(orig, 2, STATS = ms, FUN = "-")  # 2nd dimension is columns, removing array of means, function = subtract
normalized <- sweep(normalized, 2, STATS = sds, FUN = "/")  # 2nd dimension is columns, scaling by array of sds, function = divide
head(normalized)  # now a dataframe of Z scores
```

```{r}
M <- as.matrix(normalized)
```

```{r}
U = chol(R)
newM = M %*% U
new = as.data.frame(newM)
names(new) = c("Y", "X1", "X2", "X3")
cor(new)
```

```{r}
plot(orig)
plot(new)
```

```{r}
df <- sweep(new, 2, STATS = sds, FUN = "*")  # scale back out to original mean...
df <- sweep(df, 2, STATS = ms, FUN = "+")  # and standard deviation
head(df)
cor(df)
```

```{r}
plot(df)
```

## Challenge 1

```{r, message = FALSE}
library(ggplot2)
require(gridExtra)
```


```{r}
g1 <- ggplot(data = df, aes(x = X1, y = Y)) + geom_point() + geom_smooth(method = "lm",
    formula = y ~ x)
g2 <- ggplot(data = df, aes(x = X2, y = Y)) + geom_point() + geom_smooth(method = "lm",
    formula = y ~ x)
g3 <- ggplot(data = df, aes(x = X3, y = Y)) + geom_point() + geom_smooth(method = "lm",
    formula = y ~ x)
grid.arrange(g1, g2, g3, ncol = 3)
```

```{r}
m1 <- lm(data = df, formula = Y ~ X1)
summary(m1)
```

```{r}
m2 <- lm(data = df, formula = Y ~ X2)
summary(m2)
```

```{r}
m3 <- lm(data = df, formula = Y ~ X3)
summary(m3)
```
```{r}
m <- lm(data = df, formula = Y ~ X1 + X2 + X3)
coef(m)
summary(m)
```
```{r}
plot(fitted(m), residuals(m))
hist(residuals(m))
qqnorm(residuals(m))
```
```{r}
f <- (summary(m)$r.squared * (nrow(df) - (ncol(df) - 1) - 1))/((1 - summary(m)$r.squared) *
    (ncol(df) - 1))
f
```

## Challenge 2

```{r, message=FALSE}
library(curl)
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall21/zombies.csv")
z <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = TRUE)
head(z)
```

```{r}
m <- lm(data = z, height ~ weight + age)
summary(m)
```

ANCOVA
```{r}
library(car)
m <- lm(data = z, formula = height ~ gender + age)
summary(m)
```
```{r}
m.aov <- Anova(m, type = "II")
m.aov
```
```{r}
plot(fitted(m), residuals(m))
hist(residuals(m))
qqnorm(residuals(m))
```

```{r}
library(ggplot2)
p <- ggplot(data = z, aes(x = age, y = height)) + geom_point(aes(color = factor(gender))) +
    scale_color_manual(values = c("goldenrod", "blue"))
p <- p + geom_abline(slope = m$coefficients[3], intercept = m$coefficients[1],
    color = "goldenrod4")
p <- p + geom_abline(slope = m$coefficients[3], intercept = m$coefficients[1] +
    m$coefficients[2], color = "darkblue")
p
```

CI and Prediction
```{r}
m <- lm(data = z, formula = height ~ age + gender)
summary(m)
confint(m, level = 0.95)
```

## Challenge 3
```{r}
ci <- predict(m, newdata = data.frame(age = 29, gender = "Male"), interval = "confidence",
    level = 0.95)
ci
```

```{r}
pi <- predict(m, newdata = data.frame(age = 29, gender = "Male"), interval = "prediction",
    level = 0.95)
pi
```

Interactions between Predictions

```{r}
m <- lm(data = z, height ~ age + gender + age:gender)  # or
summary(m)
```

```{r}
m <- lm(data = z, height ~ age * gender)
summary(m)
coefficients(m)

```

```{r}
library(ggplot2)
library(gridExtra)
p1 <- ggplot(data = z, aes(x = age, y = height)) + geom_point(aes(color = factor(gender))) +
    scale_color_manual(values = c("goldenrod", "blue"))
p1 <- p1 + geom_abline(slope = m$coefficients[2], intercept = m$coefficients[1],
    color = "goldenrod4")
p1 <- p1 + geom_abline(slope = m$coefficients[2] + m$coefficients[4], intercept = m$coefficients[1] +
    m$coefficients[3], color = "darkblue")
p1
```

```{r}
p2 <- ggplot(data = z, aes(x = age, y = height)) + geom_point(aes(color = factor(gender))) +
    scale_color_manual(values = c("goldenrod", "blue")) + geom_smooth(method = "lm",
    aes(color = factor(gender), fullrange = TRUE))
grid.arrange(p1, p2, ncol = 2)
```

## Challenge 4
```{r}
library(dplyr)
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall21/KamilarAndCooperData.csv")
d <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = TRUE)
head(d)
```

```{r}
d <- select(d, Brain_Size_Female_Mean, Family, Body_mass_female_mean, MeanGroupSize,
    DayLength_km, HomeRange_km2, Move)
```

```{r}
m <- lm(data = d, log(HomeRange_km2) ~ log(Body_mass_female_mean) + log(Brain_Size_Female_Mean) +
    MeanGroupSize + Move)
summary(m)
```

```{r}
plot(m$residuals)
qqnorm(m$residuals)
```

```{r}
shapiro.test(m$residuals)
```


```{r}
m <- lm(data = d, log(HomeRange_km2) ~ log(Body_mass_female_mean) + log(Brain_Size_Female_Mean) +
    MeanGroupSize)
summary(m)
```
```{r}
plot(m$residuals)
qqnorm(m$residuals)
```

```{r}
shapiro.test(m$residuals)  # no significant deviation from normal
```

