---
title: "Mod 3-5 (Wk 2)"
author: "Julianna D."
date: "2023-09-14"
output: html_document
---
# Module 3 Reproducible Research in RMarkdown
Setting up Git & linking Repo

# Module 4 Working w/ Data Structures
```{r}
library(stringr)
```

## Challenge 1
```{r}
ulysses<-c("Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed.")
stringr::str_split(ulysses,pattern=" ",n=22)
```

```{r}
u2<-stringr::str_split(string=(gsub("[[:punct:]]","",ulysses)),pattern=" ",n=22)
u2[seq(from=1,to=22,by=3)]
```

```{r}
m <- matrix(data=1:80,nrow=8,ncol=10,byrow=FALSE)
m
```

```{r}
x <- m[4,5]
x
```

## Challenge 2
```{r}
x<-m[,c(2,3,6)]
x
```

```{r}
x<-m[c(6,8),]
x
```

```{r}
x<-m[c(2:6),c(2:9)]
x
```
## Challenge 3

```{r}
a <- array(data=400:1,dim=c(5,5,4,4))
a
```
```{r}
a[1, 1, 1, 2]
```

```{r}
a[2, 3, 2, ]
```

```{r}
a[1:5, 1:5, 3, 3]
```

Overwriting
```{r}
m[7,1] <- 564
m[,8] <- 2
m[2:5,4:8] <- 1
m[2:5,4:8] <- c(20,19,18,17)
m[2:5,4:8] <- matrix(data = c(20:1), nrow=4,ncol=5,byrow=TRUE)
m[,8] <- c("a","b")
```

Lists and Data Frames
```{r}
s <- c("this","is","a","vector","of","strings") # vector
m <- matrix(data=1:40, nrow=5, ncol=8) # this is a matrix
b <- FALSE 
l <- list(s, m, b) 
l
```

```{r}
l[[2]] 
l[[2]][2,6]
l[1:2] 
l[c(1,3)]
```

```{r}
str(l)
```

```{r}
names(l) <- c("string", "matrix", "logical")
names(l)
```

```{r}
l$string 
```

```{r}
l$matrix[3,5]
```

## Challenge 4
```{r}
# Getting Started w/ provided code for Strepsirhini
Lemuroidea<-c("Cheirogaleidae","Lepilemuridae","Indriidae","Lemuridae","Daubentoniidae")
Lorisoidea<-c("Lorisidae","Galagidae")
Strepsirhini<-list(Lemuroidea,Lorisoidea)
names(Strepsirhini)<-list("Lemuroidea","Lorisoidea")
Strepsirhini
```
```{r}
# for Haplorhini
Tarsioidea <- c("Tarsiidae")
Catarrhini <- c("Cercopithecidae", "Hylobatidae", "Hominidae")
Platyrrini <- c("Cebidae", "Atelidae", "Pitheciidae")
Anthropoidea <- list(Catarrhini, Platyrrini)
names(Anthropoidea) <- list("Catarrhini", "Platyrrini")
Haplorhini <- list(Anthropoidea, Tarsioidea)
names(Haplorhini) <- list("Anthropoidea", "Tarsioidea")
Haplorhini
```

```{r}
# Full list
Platyrrini <- c("Cebidae", "Atelidae", "Pitheciidae")
Catarrhini <- c("Cercopithecidae", "Hylobatidae", "Hominidae")
Tarsioidea <- c("Tarsiidae")
Anthropoidea <- list(Platyrrini,Catarrhini)
names(Anthropoidea) <- list("Platyrrini", "Catarrhini")
Tarsioidea <- c("Tarsiidae")
Haplorhini <- list(Anthropoidea, Tarsioidea)
names(Haplorhini) <- list("Anthropoidea", "Tarsioidea")
Haplorhini
Lorisoidea <- c("Lorisidae", "Galagidae")
Lemuroidea <- c("Cheirogaleidae", "Lepilemuridae", "Indriidae", "Lemuridae", "Daubentoniidae")
Strepsirhini <- list(Lorisoidea,Lemuroidea)
names(Strepsirhini) <- list("Lorisoidea", "Lemuroidea")
Strepsirhini
Primates <- list(Haplorhini, Strepsirhini)
names(Primates) <- list("Haplorhini", "Strepsirhini")
Primates
```

## Challenge 5
Data Frames
```{r}
m3<-matrix(data=c(3, 0, 1 ,23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2),nrow=5,ncol=3,byrow=TRUE)
m3
```

```{r}
m3<-as.data.frame(m3)
m3
```

```{r}
m3$V2<-as.logical(m3$V2)
m3
```

```{r}
m3$V3<-as.factor(m3$V3)
m3
```

```{r}
str(m3)
```

# Module 5 Getting Data into R
```{r}
library(readr)
```

can also use file.choose()
```{r}
f <- "~/Desktop/CPDS-1960-2014-reduced.txt"
d <- read.table(f, header = TRUE, sep =",", stringsAsFactors = FALSE, fill=T)
head(d) # lists the first 6 lines of data
```

```{r}
tail(d)
class(d)
```

```{r}
d <- read.delim(f, header = TRUE, stringsAsFactors = FALSE)
head(d)
```
```{r}
f <- "~/Desktop/CPDS-1960-2014-reduced.csv"
d <- read.table(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(d)
```
```{r}
d <- read.csv(f, header = TRUE, stringsAsFactors = FALSE)
head(d)
```
```{r}
require(readr)
f <- "~/Desktop/CPDS-1960-2014-reduced.txt"
d <- read_tsv(f, col_names = TRUE)
```
```{r}
head(d)
class(d)
```

```{r}
d <- read_delim(f, delim = "\t", col_names = TRUE)
head(d)
```

```{r}
require(readr)
f <- "~/Desktop/CPDS-1960-2014-reduced.csv"
d <- read_csv(f, col_names = TRUE)
head(d)
```

```{r}
d <- read_delim(f, delim = ",", col_names = TRUE)
head(d)
```
```{r}
require(readxl)
f <- "~/Desktop/CPDS-1960-2014-reduced.xlsx"
d <- read_excel(f, sheet = 1, col_names = TRUE)
head(d)
str(d)
```

```{r}
library(curl)
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall23/CPDS-1960-2014-reduced.csv")
d <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(d)
```

```{r}
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall23/CPDS-1960-2014-reduced.txt")
d <- read.table(f, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
head(d)
```

```{r}
Sys.setenv(VROOM_CONNECTION_SIZE = 131072 * 2)
library(readr)
f <- "https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall23/CPDS-1960-2014-reduced.csv"
d <- read_csv(f, col_names = TRUE)
head(d)
```

```{r}
f <- "https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall23/CPDS-1960-2014-reduced.txt"
d <- read_tsv(f, col_names = TRUE)
head(d)
```

