---
title: "Mod 8 (wk 4)"
author: "Julianna D."
date: "2023-09-28"
output: html_document
---

# Module 8 Probabilities and Distributions

## Challenge 1
```{r}
nrolls <- 1000
roll <- function(x) {
    sample(1:6, x, replace = TRUE)
}
two_dice <- roll(nrolls) + roll(nrolls)
hist(two_dice, breaks = c(1.5:12.5), probability = TRUE, main = "Rolling Two Dice",
    xlab = "sum of rolls", ylab = "probability")
```


## Challenge 2  

Rules of Probability
-- Wrote on paper

Random Variables
```{r}
#Flipping a fair coin
outcomes <- c("heads", "tails")
prob <- c(1/2, 1/2)
barplot(prob, ylim = c(0, 0.6), names.arg = outcomes, space = 0.1, xlab = "outcome",
    ylab = "Pr(X = outcome)", main = "Probability Mass Function")
```

```{r}
cumprob <- cumsum(prob)
barplot(cumprob, names.arg = outcomes, space = 0.1, xlab = "outcome", ylab = "Cumulative Pr(X)",
    main = "Cumulative Probability")
```

```{r}
# Rolling a Fair Die
outcomes <- c(1, 2, 3, 4, 5, 6)
prob <- c(1/6, 1/6, 1/6, 1/6, 1/6, 1/6)
barplot(prob, ylim = c(0, 0.5), names.arg = outcomes, space = 0.1, xlab = "outcome",
    ylab = "Pr(X = outcome)", main = "Probability Mass Function")
```

```{r}
cumprob <- cumsum(prob)
barplot(cumprob, names.arg = outcomes, space = 0.1, xlab = "outcome", ylab = "Cumulative Pr(X)",
    main = "Cumulative Probability")
```

## Challenge 3


## Challenge 4
```{r}
n <- 6  # number of trials
k <- 6  # number of successes
p <- 1/6
prob <- (factorial(n)/(factorial(k) * factorial(n - k))) * (p^k) * (1 - p)^(n -
    k)
prob
```

```{r}
k <- 3  # number of successes
prob <- (factorial(n)/(factorial(k) * factorial(n - k))) * (p^k) * (1 - p)^(n -
    k)
prob
```

```{r}
dbinom(x = k, size = n, prob = p)
```

```{r}
probset <- dbinom(x = 0:6, size = 6, prob = 1/6)  # x is number of successes, size is number of trials
barplot(probset, names.arg = 0:6, space = 0, xlab = "outcome", ylab = "Pr(X = outcome)",
    main = "Probability Mass Function")
```

```{r}
cumprob = cumsum(probset)
barplot(cumprob, names.arg = 0:6, space = 0.1, xlab = "outcome", ylab = "Cumulative Pr(X)",
    main = "Cumulative Probability")
```

```{r}
sum(probset)
dbinom(x=3, size=6, prob=1/6)
pbinom(q=3, size=6, prob=1/6)

#more than 3 rolls of "1"
1-pbinom(q=3, size=6, prob=1/6)
```

## Challenge 5
```{r}
a <- 4
b <- 8
x <- seq(from = a - (b - a), to = b + (b - a), by = 0.01)
fx <- dunif(x, min = a, max = b)  # dunif() evaluates the density at each x
plot(x, fx, type = "l", xlab = "x", ylab = "f(x)", main = "Probability Density Function")
```

```{r}
plot(x, punif(q = x, min = a, max = b), type = "l", xlab = "x", ylab = "Pr(X ≤ x)",
    main = "Cumulative Probability")
```

#3 Challenge 6
```{r}
mu <- 4
sigma <- 1.5
curve(dnorm(x, mu, sigma), mu - 4 * sigma, mu + 4 * sigma, main = "Normal Curve",
    xlab = "x", ylab = "f(x)")
```

```{r}
p <- pnorm(8, mean = 6, sd = 2) - pnorm(7, mean = 6, sd = 2)
p
```

```{r}
mu <- 0
sigma <- 1
p <- pnorm(mu + 2 * sigma, mean = mu, sd = sigma) - pnorm(mu - 2 * sigma, mean = mu,
    sd = sigma)
p
```

```{r}
p <- pnorm(mu + 1 * sigma, mean = mu, sd = sigma) - pnorm(mu - 1 * sigma, mean = mu,
    sd = sigma)
p
```

## Challenge 7
```{r}
n <- 1000
mu <- 3.5
sigma <- 4
v <- rnorm(n, mu, sigma)
mean(v)
var(v)
sd(v)
```

```{r}
hist(v, breaks=seq(from = -15, to = 20, by = 0.5), probability = TRUE)
```

```{r}
qqnorm(v, main = "Normal QQ plot random normal variables")
qqline(v, col = "gray")
```

```{r}
# Step 1
p <- ppoints(length(v))
head(p)
tail(p)
```

```{r}
# Step 2
theoretical_q <- qnorm(ppoints(length(v)))
```

```{r}
# Step 3
observed_q <- quantile(v, ppoints(v))
```

```{r}
#Step 4
plot(theoretical_q, observed_q, main = "Normal QQ plot random normal variables",
    xlab = "Theoretical Quantiles", ylab = "Sample Quantiles")
```

## Challenge 8
```{r}
x <- rnorm(10000, mean = 5, sd = 8)  # simulate from a normal distribution with mean 5 and SD 8
hist(x)
```

```{r}
mean(x)
sd(x)
```

```{r}
z <- (x - mean(x))/sd(x)  # standardized!
hist(z)
```

```{r}
mean(z)
sd(z)
```

Sample Populations vs Population Dist
```{r}
set.seed(1)
x <- rnorm(1e+06, 25, 5)
hist(x, probability = TRUE)
```

```{r}
mu <- mean(x)
mu
sigma <- sqrt(sum((x - mean(x))^2)/length(x))
```

```{r}
k <- 1000  # number of samples
n <- 5  # size of each sample
s <- NULL  # dummy variable to hold each sample
for (i in 1:k) {
    s[[i]] <- sample(x, size = n, replace = FALSE)
}
head(s)
```

```{r}
m <- NULL
for (i in 1:k) {
    m[i] <- mean(s[[i]])
}
mean(m)
mu
```

```{r}
pop_se <- sqrt(sigma^2/n)
pop_se
```

```{r}
stdev <- NULL
for (i in 1:k) {
    stdev[i] <- sd(s[[i]])
}
sem <- stdev/sqrt(n)  # a vector of SEs estimated from each sample 
head(sem)
```

```{r}
mean(sem)
pop_se
```

